apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: helloworld.alw6e85l6k816dme7oawdycsud7uyca5.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world
          servicePort: 80